[global]
proxy = true
proxy_url = "http://127.0.0.1:50051"

[models.claude]
model = "claude-opus-4-20250514"
max_tokens = 1024
anthropic_api_key = "${ANTHROPIC_API_KEY}"
url = "https://api.anthropic.com/"

# Future models can be added here, e.g.:
# [models.openai]
# model = "gpt-4o"
# max_tokens = 1024
# api_key = "${OPENAI_API_KEY}"
# url = "https://api.openai.com/"
